[book]
title = "Resql"
description = "SQL-files-as-REST-endpoints microservice"
authors = ["Rainer Türner"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/turnerrainer/Resql"
edit-url-template = "https://github.com/turnerrainer/Resql/edit/dev/book/{path}"

[output.linkcheck]
follow-web-links = false
warning-policy = "error"
